/* ВЗАИМОДЕЙСТВИЯ С ЭЛЕМЕНТАМИ ПО АТРИБУТАМ */
$('a[download]').css('border', '1px solid red'); // простой атрибут
$('a[href="http://ya.ru"]').css('border', '1px solid red'); // полное соответствие
$('a[href!="http://ya.ru"]').css('border', '1px solid red'); // полное несоответствие
$('a[href^="http"]').css('border', '1px solid red'); // начинается на ...
$('a[href$=".com"]').css('border', '1px solid red'); // заканчивается на ...
$('a[href*="google"]').css('border', '1px solid red'); // содержит ...
$('a[data-target|="main"]').css('border', '1px solid red'); // имеет префикс - ...
$('a[href][download]').css('border', '1px solid red'); // имеет обновременно несколько атрибутов